### ISSUE TITLE
在搬瓦工上试了，还是连不上pptp啊

### ISSUE THREAD

**Issue by sky0014** [pexcn/net-speeder#4]
@pexcn 你那边可以么

**Comment by pexcn** [comment]
pptp被干扰了吧，现在怎么还在用？

**Comment by sky0014** [comment]
你的代码在我的机器上运行不正常，tcp偏移不对，可能是大小端问题，调了一晚上总算在我机器上成功过滤了1723端口，然后还是连不上，累哭了。
请问你说怎么还在用时什么意思，现在应该用哪个呢？

**Comment by pexcn** [comment]
我以前试过，可以用。现在pptp被干扰得很厉害了。

**Comment by sky0014** [comment]
抓了一下午包对比，终于搞定了：）
指定只对TCP协议生效就好了，PPTP建立连接相关的协议就被排除掉了，之前一直是指定全部IP协议
`./netspeeder venet0 "tcp"`
感谢你的分享

**Comment by pexcn** [comment]
我之前一直是`netspeeder venet0 "src port xxx || src port xxx"`
